
//#define DONT_USE_GENERATE_CODE                                                                 
//------------------------------------------------------------------------------                 
// <auto-generated>                                                                              
//     This code was generated by Lockstep.CodeGenerator                                         
//                                                                                               
//     Changes to this file may cause incorrect behavior and will be lost if                     
//     the code is regenerated.                                                                  
//     https://github.com/JiepengTan/LockstepPlatform                                            
// </auto-generated>                                                                             
//------------------------------------------------------------------------------                 
                                                                                                 
using Lockstep.Util;                                                                    
using Lockstep.Serialization;                                                                    
using Lockstep.Math;                                                                    
using Lockstep.Game;                                                                    
using Lockstep.Collision2D;                                                                    
using System.Text;                                                                          
#if !DONT_USE_GENERATE_CODE                                                                      

namespace Lockstep.Game{                                                                                               
    public partial class PlayerInput :IBackup{                                                                  
       public void WriteBackup(Serializer writer){                                           
			writer.Write(Deg);
			writer.Write(SkillId);                                                                                     
       }                                                                                            
                                                                                                    
       public void ReadBackup(Deserializer reader){                                       
			Deg = reader.ReadUInt16();
			SkillId = reader.ReadUInt16();                                                                                     
       }                                                                                            
                                                                                                    
       public int GetHash(ref int idx){                                      
           int hash = 1;                                                                             
			hash += Deg.GetHash(ref idx) * PrimerLUT.GetPrimer(idx++);
			hash += SkillId.GetHash(ref idx) * PrimerLUT.GetPrimer(idx++);                                                                                     
           return hash;                                                                                    
       }                                                                                            
                                                                                                    
       public void DumpStr(StringBuilder sb,string prefix){                                       
			sb.AppendLine(prefix + "Deg"+":" + Deg.ToString());
			sb.AppendLine(prefix + "SkillId"+":" + SkillId.ToString());                                                                                     
       }                                                                                            
    }                                                               
}                                                              
                                                                              
#endif                                                                                           
                                                                                              